schema_version: 1

context:
  python_min: "3.11"
  version: "0.0.8"

package:
  name: mdadash
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/m/mdadash/mdadash-${{ version }}.tar.gz
  sha256: 4c3ef424190f8e2ffdf41d46feaac0d2e9219bc74fc85c5e49ee7aa9cc086f7a

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - mdadash = mdadash.backend.main:start_server

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=77
    - versioningit
    - pip
  run:
    - python >=${{ python_min }}
    - fastapi >=0.136.3
    - imdclient >=0.2.3
    - ipykernel >=7.2.0
    - mdanalysis >=2.10.0
    - python-socketio >=5.16.2
    - uvicorn >=0.47.0

tests:
  - python:
      imports:
        - mdadash
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"
  - requirements:
      run:
        - python ${{ python_min }}.*
    script:
      - mdadash --help

about:
  summary: Dashboard for tracking and analyzing live MD simulations with streaming.
  license: MIT
  license_file: LICENSE
  homepage: https://pypi.org/project/mdadash/

extra:
  recipe-maintainers:
    - PardhavMaradani
